---
title: "NanoQuRe Sequencing QC Report"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    theme: sandstone      
    highlight: tango    
    toc: true           #Table of content
    toc_float:
      collapsed: false  # This keeps the menu open so you see all plots
      smooth_scroll: true # Makes the transition "glide" when clicked
    code_folding: hide
params:
  data: NULL
---


```{r setup, include=FALSE}
library(NanoQuRe)
library(dplyr)
library(ggplot2)
```




## Sequencing Statistics Table
```{r, echo=FALSE}
DT::datatable(sequencing_stats(params$data), caption = 'Table 1: Sequencing Summary Statistics')
```




## Quality Statistics Table
```{r, echo=FALSE}
DT::datatable(quality_stats(params$data), caption = 'Table 1: Sequencing Summary Quality Statistics')
```




## Read Lengths
```{r, echo=FALSE}
plot_read_lengths(params$data)
```




## Cumulative Yield
```{r, echo=FALSE}
plot_cumulative_yield(params$data)
```




## Quality Distribution
```{r, echo=FALSE}
plot_quality_distribution(params$data)
```




## Average Speed
```{r, echo=FALSE}
plot_average_speed(params$data)
```




## Sequencing Throughput
```{r, echo=FALSE}
plot_seq_throughput(params$data)
```




## Channel Activity
```{r, echo=FALSE}
plot_active_channels(params$data)
```




## Length and Qscore
```{r, echo=FALSE}
double_results <- plot_double(params$data)
double_results$length
double_results$qscore
```



