---
title: "seq_throughput"
output: html_document
---

```{r}
cum_ela <- ligase_ela %>% select(c(start_time,duration, passes_filtering, sequence_length_template))
sampl_id = first(ligase_ela$sample_id)
pass_cum_ela <- cum_ela %>% filter(passes_filtering==TRUE)
fail_cum_ela <- cum_ela %>% filter(passes_filtering==FALSE)
```



```{r}
pass_cum_ela <- pass_cum_ela %>% arrange(pass_cum_ela$start_time)
fail_cum_ela <- fail_cum_ela %>% arrange(fail_cum_ela$start_time)

#df %>% mutate(sales_tax = price * 0.075)
pass_cum_ela %>% mutate(start_time = start_time/3600)
fail_cum_ela %>% mutate(start_time = start_time/3600)
```


```{r}
cumul_plot <- function(my_data){
  sample_name <-  first(my_data$sample_id)
  cum_data <- my_data %>% select(c(start_time,duration, passes_filtering, sequence_length_template))
  
  pass_cum <- cum_data %>% filter(passes_filtering==TRUE)
  fail_cum <- cum_data %>% filter(passes_filtering==FALSE)
  pass_cum <- pass_cum %>% arrange(pass_cum$start_time)
  fail_cum <- fail_cum %>% arrange(fail_cum$start_time)

pass_cum <- pass_cum %>% mutate(h_start_time = start_time/3600)
fail_cum <- fail_cum %>% mutate(h_start_time = start_time/3600)
print(pass_cum)
  
data <- ggplot(data = pass_cum) + aes(x = h_start_time)
plot_line <- geom_freqpoly(color = "skyblue")
axis_limit <- coord_cartesian(xlim = c(0, 75), ylim = c(0, 40000))


length_plot <- data + plot_line
}
```


```{r}
cum_plot <- cumul_plot(ligase_ela)
cum_plot
```


#1 Gigabase (Gb): 1,000,000,000 bases <<< 1 * 10^9
```{r}

pass_fail <- geom_histogram(binwidth = 0.09, color = "black", position = "stack")
qscore_line <- geom_vline(aes(xintercept = 7), color = "orange")
axis_limit <- coord_cartesian(xlim = c(0, 15), ylim = c(0, 40000))
plot_lable <-  labs(title = paste0("Quality distribuion ", sample_name), x = "Mean Q score of read", y = "No of reads")


n50_label <- annotate(geom = "text", x = 7, y = 39999, label = paste("Q score cut-off"), color = "orange", fontface = "bold", size = 4)


```


```{r}

cumul_plot <- function(my_data){
  sample_name <-  first(my_data$sample_id)
  cum_data <- my_data %>% select(c(start_time,duration, passes_filtering, sequence_length_template))
  
  pass_cum <- cum_data %>% filter(passes_filtering==TRUE)
  fail_cum <- cum_data %>% filter(passes_filtering==FALSE)
  pass_cum <- pass_cum %>% arrange(pass_cum$start_time)
  fail_cum <- fail_cum %>% arrange(fail_cum$start_time)

pass_cum <- pass_cum %>% mutate(h_start_time = start_time/3600)
pass_cum <- pass_cum %>% mutate(bases_gb = cumsum(pass_cum$sequence_length_template) / 1e9)

fail_cum <- fail_cum %>% mutate(h_start_time = start_time/3600)
fail_cum <- fail_cum %>% mutate(bases_gb = cumsum(fail_cum$sequence_length_template) / 1e9)

print(pass_cum)
  
data <- ggplot(data = pass_cum) + aes(x = h_start_time, y=bases_gb)
plot_line <- geom_line(linewidth = 1)
axis_limit <- coord_cartesian(xlim = c(0, 75), ylim = c(0, 40000))


cum_plot <- data + plot_line + axis_limit
}
```


```{r}
cum_plot <- cumul_plot(ligase_ela)
cum_plot
```

