---
title: "plot_cumulative_yield()"
output: html_document
---

```{r}
cum_ela <- ligase_ela %>% select(c(start_time,duration, passes_filtering, sequence_length_template))
sampl_id = first(ligase_ela$sample_id)
pass_cum_ela <- cum_ela %>% filter(passes_filtering==TRUE)
fail_cum_ela <- cum_ela %>% filter(passes_filtering==FALSE)
```

```{r}
pass_cum_ela <- pass_cum_ela %>% arrange(pass_cum_ela$start_time)
fail_cum_ela <- fail_cum_ela %>% arrange(fail_cum_ela$start_time)

#df %>% mutate(sales_tax = price * 0.075)
pass_cum_ela %>% mutate(start_time = start_time/3600)
fail_cum_ela %>% mutate(start_time = start_time/3600)
```


```{r}
plot_cumulative_yield <- function(my_data){
  sample_name <-  first(my_data$sample_id)
  cum_data <- my_data %>% select(c(start_time,duration, passes_filtering, sequence_length_template))
  
  pass_cum <- cum_data %>% filter(passes_filtering==TRUE) %>% arrange(start_time)
  fail_cum <- cum_data %>% filter(passes_filtering==FALSE) %>% arrange(start_time)
#print(pass_cum)
pass_cum <- pass_cum %>% mutate(h_start_time = start_time/3600,
  bases_gb = cumsum(as.numeric(sequence_length_template)) / 1e9, 
  pass_status = "pass")

fail_cum <- fail_cum %>% mutate(h_start_time = start_time/3600,
  bases_gb = cumsum(as.numeric(sequence_length_template)) / 1e9, 
  pass_status = "fail")

print(pass_cum)
print(fail_cum) 

pass_fail_tab <- dplyr::bind_rows(pass_cum, fail_cum)

cum_data <- ggplot(pass_fail_tab, aes(x = h_start_time, y = bases_gb, color = pass_status))
cum_lines <- geom_line(linewidth = 1)
cum_labels <- labs(title = paste0("Cumulative Yield ", sample_name), x = "Time (hours)", y = "Yield (Gb)") 

cum_plot <- cum_data + cum_lines + cum_labels
cum_plot

}


#pass_fail_tab <- plot_cumulative_yield()(ligase_ela)
```


```{r}
cum_data <- ggplot(pass_fail_tab, aes(x = h_start_time, y = bases_gb, color = pass_status))
cum_lines <- geom_line(linewidth = 1)
cum_labels <- labs(title = "Cumulative Yield ", x = "Time (hours)", y = "Yield (Gb)") 



cum_plot <- cum_data + cum_lines + cum_labels
cum_plot
```

```{r}
plot3 <- plot_cumulative_yield(sample_data)
plot3
```



