---
title: "plot_read_lengths"
output: html_document
---

```{r}
mean_length_ela = mean(ligase_ela$sequence_length_template)
max_y_mean <- max(count_seq$n, na.rm = TRUE)

```

```{r}
bs_n50_ela <- Biostrings::N50(ligase_ela$sequence_length_template)
max_y_n50 <- max(count_seq$n, na.rm = TRUE)
```



```{r}
count_seq <- ligase_ela %>% dplyr::count(sequence_length_template)
```

```{r}
data <- ggplot(data = count_seq) + aes(x = sequence_length_template, y = n)
bar_color <- geom_col(color = "skyblue")
mean_lengt <- geom_vline(aes(xintercept = mean_length_ela), color = "purple")
n50_line <- geom_vline(aes(xintercept = bs_n50_ela), color = "darkgreen")
axis_limit <- coord_cartesian(xlim = c(0, 4000), ylim = c(0, 10000))
plot_lable <-  labs(title ="Length plot", x = "Sequence length [nt]", y = "No of bases sequenced")

mean_label <- annotate(geom = "text", x = mean_length_ela* 0.5, y = max_y_mean * 0.65, label = paste("Mean Length"), color = "purple", fontface = "bold", size = 4)

n50_label <- annotate(geom = "text", x = bs_n50_ela* 2.5, y = max_y_n50 * 0.65, label = paste("N50"), color = "darkgreen", fontface = "bold", size = 4)


length_plot <- data + bar_color + mean_lengt + n50_line + axis_limit + plot_lable + mean_label + n50_label
length_plot
```

```{r}

```


```{r}

plot_read_lengths <- function(my_data){
  count_seq <- my_data %>% dplyr::count(sequence_length_template)
  mean_length = mean(my_data$sequence_length_template)
max_y_mean <- max(count_seq$n, na.rm = TRUE)
  n50_SR <- Biostrings::N50(my_data$sequence_length_template)
  max_y_n50 <- max(count_seq$n, na.rm = TRUE)
  sample_name <-  first(my_data$sample_id)
  
  
  
  data <- ggplot(data = count_seq) + aes(x = sequence_length_template, y = n)
bar_color <- geom_col(color = "skyblue")
mean_lengt <- geom_vline(aes(xintercept = mean_length), color = "purple")
n50_line <- geom_vline(aes(xintercept = n50_SR), color = "darkgreen")
axis_limit <- coord_cartesian(xlim = c(0, 4000), ylim = c(0, 60000))
plot_lable <-  labs(title =paste0("Length plot  ", sample_name), x = "Sequence length [nt]", y = "No of bases sequenced")

mean_label <- annotate(geom = "text", x = mean_length* 2.5, y = max_y_mean * 0.65, label = paste("Mean Length"), color = "purple", fontface = "bold", size = 4)
n50_label <- annotate(geom = "text", x = n50_SR* 2.5, y = max_y_n50 * 0.65, label = paste("N50"), color = "darkgreen", fontface = "bold", size = 4)

length_plot <- data + bar_color + mean_lengt + n50_line + axis_limit + plot_lable + mean_label + n50_label
length_plot
}
```

```{r}
leng_plot_database <- lapply(seqsum_database, plot_read_lengths)
leng_plot_database
```

```{r}
plot1 <- plot_read_lengths(sample_data)
plot1
```









```{r}
plot_read_lengths <- function(my_data){
  
   assertthat::assert_that(assertthat::has_name(my_data, "sequence_length_template"),
                          msg = "The data frame is missing the 'sequence_length_template' column")

  assertthat::assert_that(assertthat::has_name(my_data, "sample_id"),
                          msg = "The data frame is missing the 'sample_id' column")

  count_seq <- my_data %>% dplyr::count(sequence_length_template)
  max_y_mean <- max(count_seq$n, na.rm = TRUE)
  mean_length = mean(my_data$sequence_length_template)
  n50_SR <- calculate_n50(my_data)
  max_y_n50 <- max(count_seq$n, na.rm = TRUE)
  sample_name <-  dplyr::first(my_data$sample_id)

  data <- ggplot2::ggplot(data = count_seq) + ggplot2::aes(x = sequence_length_template, y = n)
  bar_color <- ggplot2::geom_col(color = "skyblue")
  mean_length_line <- ggplot2::geom_vline(ggplot2::aes(xintercept = mean_length), color = "purple")
  n50_line <- ggplot2::geom_vline(ggplot2::aes(xintercept = n50_SR), color = "darkgreen")
  axis_limit <- ggplot2::coord_cartesian(xlim = c(0, 4000), ylim = c(0, 10000))
  plot_lable <-  ggplot2::labs(title =paste0("Length plot  ", sample_name), x = "Sequence length [nt]", y = "No of bases sequenced")

  mean_label <- ggplot2::annotate(geom = "text", x = mean_length* 2.5, y = max_y_mean * 0.65, label = paste("Mean Length"), color = "purple", fontface = "bold", size = 4)
  n50_label <- ggplot2::annotate(geom = "text", x = n50_SR* 2.5, y = max_y_n50 * 0.65, label = paste("N50"), color = "darkgreen", fontface = "bold", size = 4)

  length_plot <- data + bar_color + mean_length + n50_line + axis_limit + plot_lable + mean_label + n50_label
  return(length_plot)
}

```


```{r}
plot1 <- plot_read_lengths(ligase_ela)
plot1
```



